# NAME: Miles Kang,Michelle Zhuang
# EMAIL: milesjkang@gmail.com,michellezhuang@g.ucla.edu
# ID: 405106565,505143435

# Program is written in Python3

default:
	rm -f lab3b
	ln lab3b.py lab3b
	chmod +x lab3b
clean:
	rm -f lab3b lab3b-405106565.tar.gz
dist:
	tar -czvf lab3b-405106565.tar.gz lab3b.py Makefile README
