#NAME: Miles Kang
#EMAIL: milesjkang@gmail.com
#ID: 405106565

default:
	gcc -Wall -Wextra -g -o lab0 lab0.c
check:
	./check.sh
clean:
	rm -f lab0 *.txt *.tar.gz
dist:
	tar -czvf lab0-405106565.tar.gz lab0.c Makefile *.png README check.sh
