# NAME: Miles Kang
# EMAIL: milesjkang@gmail.com
# ID: 405106565

default:
	gcc -Wall -Wextra -g -o lab1a lab1a.c
clean:
	rm -f lab1a *.tar.gz
dist:
	tar -czvf lab1a-405106565.tar.gz lab1a.c Makefile README
